# Configuration file for Sea of Clouds - Twitter Widget

username: boltcm
avatar_size: 40
count: 3
fetch: 20
loading_text: 'Loading tweets…'

# Change these, if you want to use your own templates (inside this extension's assets/ folder)
# Do _not_ change the default files themselves, because they will be overwritten with updates
# of this extension.
style_filename: jquery.tweet.css
template: tweetwidget.twig
